Pipfile
app/app.py
app/static/copy.js
app/templates/output.html
app/templates/sealed-secret.yaml

- Print out complete sealedSecret kubernetes object after encrypting
- modified the flask logs
- custom logging after sealedSecret has been created
- modified the copy.js for dynamic tooltips

Print out Kubernetes Object and improved logging

---

chart/kubeseal-webgui/templates/service.yaml

Fix typo in Service.yaml

---

api/app/kubeseal.py

Signed-off-by: Johannes Siebel <johannes.siebel@gmail.com>

hotfix: changed log level of request content to debug

---

chart/kubeseal-webgui/templates/deployment.yaml
chart/kubeseal-webgui/templates/service.yaml

Signed-off-by: Johannes Siebel <johannes.siebel@gmail.com>

Fixed service port mapping

---

.gitignore
Dockerfile.api
README.md
api/app/__init__.py
api/app/kubernetes.py
api/app/kubeseal.py
api/requirements.txt
chart/kubeseal-webgui/Chart.yaml
chart/kubeseal-webgui/templates/clusterrole.yaml
chart/kubeseal-webgui/templates/clusterrolebinding.yaml
chart/kubeseal-webgui/templates/configmap.yaml
chart/kubeseal-webgui/templates/deployment.yaml
chart/kubeseal-webgui/templates/serviceaccount.yaml
chart/kubeseal-webgui/values.yaml
dev/build-api-image.sh
dev/build-ui-image.sh
dev/local-dev-minikube.sh
dev/test.js
ui/package-lock.json
ui/package.json
ui/src/components/Secrets.vue

- add select (dropdown) field for namespaces
- read current namespaces from kubernetes cluster with the python api
- update npm dependencies
- update python dependencies
- update helm chart to optionally provide a service account for reading namespaces in cluster
Closes #21 
Closes #8

Add namespaces dropdown field

---

chart/kubeseal-webgui/Chart.yaml
chart/kubeseal-webgui/templates/ingress.yaml
chart/kubeseal-webgui/values.yaml

Add optional ingressClassName value for the ingress object

---

Dockerfile.api

Fixes #145: Execute permission for shell script

---

api/kubeseal_webgui_api/config.py
api/kubeseal_webgui_api/kubernetes.py
mock/kswg_mock/routers/config.py
mock/kswg_mock/routers/kubernetes.py
mock/kswg_mock/routers/kubeseal.py
ui/src/components/AppConfig.vue
ui/src/components/Secrets.vue

This supersedes #129 (I tried to push to the original PR, but created a branch instead :()
Content is the same (extended to the new *mock* API version).

Do not escape dto

---

ui/package-lock.json
ui/package.json
ui/src/components/DarkMode.vue
ui/src/components/Secrets.vue
ui/src/main.js

Seems to be almost working. One minor cosmetic bug left in rendered secrets view

Update to Vue 3 and Bootstrap 5

---

ui/src/components/Secrets.vue

This PR is on top of the PR to convert to Vue 3.
It implements #163

List of sealed secrets

---

ui/package-lock.json
ui/package.json
ui/src/components/Secrets.vue
ui/src/main.js

Builds on top of the PRs #172 and #173

Vue select

---

.github/workflows/kind.yaml
README.md
kind-setup.sh
ui/src/components/Secrets.vue

Addresses comment in #198 that one has to add an annotation the the sealed secret, when non strict mode is used.

Add annotations

---

ui/src/components/DarkMode.vue

Seems a bit simpler to me.
Get rid of nested structure for darkMode state, which is not needed here.

Use components instead of properties based setup

---

api/kubeseal_webgui_api/app_config.py
api/kubeseal_webgui_api/routers/models.py
api/poetry.lock
api/pyproject.toml

* update to pydantic v2
* remove useless dev dependency pytest-flask

Update python deps

---

ui/src/components/Secrets.vue

no return and braces are needed here, so remove them

Simplify JS inline functions

---

ui/src/App.vue

Convert App.vue to components

---

ui/src/components/AppConfig.vue

and hopefully simplify the code by it.

Convert AppConfig to components

---

api/kubeseal_webgui_api/app.py

See https://fastapi.tiangolo.com/advanced/events/#alternative-events-deprecated

Migrate from deprecated events to lifespan functionality

---

ui/src/components/Secrets.vue

Hopefully this logic includes all possible values for secret.file. It is an Array, when initialized or empty and a File or Blob, when filled.

Fix the encrypt button state

---

chart/kubeseal-webgui/Chart.yaml
chart/kubeseal-webgui/README.md
chart/kubeseal-webgui/values.yaml

feat : update helm chart 6.0.1 version (using 4.5.1 image)
